version: '3.8'
services:
    php-apache-environment:
        container_name: docker_php_API
        build:
            context: ./
            dockerfile: Dockerfile
        depends_on:
            - db
        volumes:
            - ./:/var/www/html/
        ports:
            - 8000:80
    db:
      container_name: docker_database
      image: mysql
      ports:
          - "9906:3306"
      restart: always
      environment:
          MYSQL_ROOT_PASSWORD: " " 
          MYSQL_DATABASE: "myblog"
          MYSQL_USER: "whomafp"
          MYSQL_PASSWORD: "12345"
      